{
  branches: ["master"],
  plugins:
    [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/git",
        {
          "assets": ["version.properties"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        },
      ],
      [
        "@semantic-release/exec",
        "prepareCmd": "chmod +x ./scripts/update-version.sh && ./scripts/update-version.sh ${nextRelease.version} && chmod +x ./scripts/update-info-plist-version.sh && ./scripts/update-info-plist-version.sh",
      ],
    ],
}
