name: Bump Version

on:
  workflow_run:
    workflows:
      - "Publish to TestFlight"
    types:
      - completed
  workflow_dispatch:

jobs:
  run:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    uses: personaclick/workflow/.github/workflows/reusable-multiplatform-bump.yaml@master
    secrets:
      GITHUB_APP_ID: ${{ vars.PUBLIVERSIONER_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.PUBLIVERSIONER_SECRET }}
