name: Publish to TestFlight

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  run:
    if: github.event.pull_request.merged == true
    uses: rees46/workflow/.github/workflows/reusable-ios-testflight-publish.yaml@master
    with:
      scheme: "demo-store-ios"
      xcworkspace: "demo-store-ios.xcworkspace"
      codeSignIdentity: "Apple Distribution: M.Kechinov's web-development studio, LLC (MYA32EHWN4)"
      developmentTeam: "MYA32EHWN4"
      provisioningProfileSpecifier: "demo-ios"
    secrets:
      GITHUB_APP_ID: ${{ vars.PUBLIVERSIONER_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.PUBLIVERSIONER_SECRET }}
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_AS_BASE64_STRING }}
      IOS_CERTIFICATE_P12: ${{ secrets.IOS_CERTIFICATE_P12 }}
      IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}
