name: Sync repositories

on:
  pull_request:
    types:
      - closed
    branches:
      # - master
      - debug
  workflow_dispatch:

jobs:
  repo-sync:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.merged == true &&
       github.event.pull_request.head.ref.startsWith('release/'))
    # TODO rm
    runs-on: ubuntu-latest
    steps:
      - name: Publish log
        run: echo "sync"
    # if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    # uses: rees46/workflow/.github/workflows/reusable-ios-synchronization.yaml@master
    # permissions: write-all
    # secrets:
    #   token: ${{ secrets.JADE_SMITH_BOT_TOKEN }}
    # with:
    #   targetRepository: "personaclick/demo-ios"
    #   versionFilePath: "version.properties"
