name: Bump version

on:
  pull_request:
  # TODO uncomment
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - master
  #     - "!release/**"
  #   paths-ignore:
  #     - ".github/**"
  # workflow_dispatch:

jobs:
  run:
    # TODO uncomment
    # if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    # uses: rees46/workflow/.github/workflows/reusable-multiplatform-version-bump.yaml@master
    uses: rees46/workflow/.github/workflows/reusable-multiplatform-version-bump.yaml@feat/version-workflow
    permissions: write-all
    secrets:
      privateKey: ${{ secrets.PERSONACLICK_COURIER_SECRET }}
    with:
      reviewerUsername: iwwwanow
