name: Bump version

on:
  pull_request:
    types:
      - closed
    branches:
      # TODO uncomment
      # - master
      - debug
    paths-ignore:
      - "version.properties"

  # TODO uncomment
  # push:
  #   branches:
  #     - master
  #     - "!release/**"
  #   paths-ignore:
  #     - "version.properties"
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - master
  #     - "!release/**"
  #   paths-ignore:
  #     - ".github/**"
  # workflow_dispatch:

jobs:
  run:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    # TODO uncomment
    # uses: rees46/workflow/.github/workflows/reusable-multiplatform-version-bump.yaml@master
    uses: rees46/workflow/.github/workflows/reusable-multiplatform-version-bump.yaml@feat/version-workflow
    permissions: write-all
    secrets:
      appSecret: ${{ secrets.PERSONACLICK_COURIER_SECRET }}
    with:
      appId: ${{ vars.PERSONACLICK_COURIER_ID }}
      reviewerUsername: iwwwanow
