name: Bump version

on:
  push:
    branches:
      # TODO uncomment
      # - master
      - debug
    paths-ignore:
      - ".github/**"
      - "version.properties"
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Publish log
        run: echo "version"
    # uses: rees46/workflow/.github/workflows/reusable-multiplatform-version-bump.yaml@master
    # permissions: write-all
    # secrets:
    #   appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}
    # with:
    #   appId: ${{ vars.PUBLIVERSIONER_ID }}
    #   reviewerUsername: iwwwanow
