name: Bump version

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "version.properties"
  workflow_dispatch:

jobs:
  bump-version:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && !startsWith(github.event.pull_request.head.ref, 'release/'))
    # TODO
    # uses: rees46/workflow/.github/workflows/reusable-multiplatform-version-bump.yaml@master
    uses: rees46/workflow/.github/workflows/reusable-multiplatform-version-bump.yaml@fix/version-workflow
    permissions: write-all
    secrets:
      appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}
    with:
      appId: ${{ vars.PUBLIVERSIONER_ID }}
      reviewerUsername: iwwwanow
